apiVersion: apps/v1
kind: Deployment
metadata:
  name: taotao-cloud-uc-biz
  namespace: default
  labels:
    app: taotao-cloud-uc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taotao-cloud-uc-biz
  template:
    metadata:
      labels:
        app: taotao-cloud-uc-biz
    spec:
      containers:
        - name: taotao-cloud-uc-biz
          #image: 192.168.99.240:8443/taotao-cloud/taotao-cloud-uc:${CICD_EXECUTION_SEQUENCE}
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-uc-biz:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: taotao-cloud-uc-biz-port
              containerPort: 33337
---
apiVersion: v1
kind: Service
metadata:
  name: taotao-cloud-uc-biz
  namespace: default
  labels:
    app: taotao-cloud-uc-biz
spec:
  type: NodePort
  selector:
    app: taotao-cloud-uc-biz
  ports:
    - name: taotao-cloud-uc-biz-port
      protocol: TCP
      port: 33337
      targetPort: 33337
      nodePort: 33337
