apiVersion: apps/v1
kind: Deployment
metadata:
  name: taotao-cloud-gateway
  namespace: default
  labels:
    app: taotao-cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taotao-cloud-gateway
  template:
    metadata:
      labels:
        app: taotao-cloud-gateway
    spec:
      containers:
        - name: taotao-cloud-gateway
          #image: 192.168.99.240:8443/taotao-cloud/taotao-cloud-gateway:${CICD_EXECUTION_SEQUENCE}
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-gateway:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: taotao-cloud-gateway-port
              containerPort: 33333
---
apiVersion: v1
kind: Service
metadata:
  name: taotao-cloud-gateway
  namespace: default
  labels:
    app: taotao-cloud-gateway
spec:
  type: NodePort
  selector:
    app: taotao-cloud-gateway
  ports:
    - name: taotao-cloud-gateway-port
      protocol: TCP
      port: 33333
      targetPort: 33333
      nodePort: 33333
