apiVersion: apps/v1
kind: Deployment
metadata:
  name: taotao-cloud
  namespace: taotao-cloud-dev
  labels:
    app: taotao-cloud
    version: 2021.9.3
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: taotao-cloud
      version: 2021.9.3
      kubernetes.io/cluster-service: "true"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: taotao-cloud
        version: 2021.9.3
        kubernetes.io/cluster-service: "true"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: taotao-cloud-geteway
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-gateway:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: geteway-port
              containerPort: 9999
          env:
            - name: LOCAL_KEY
              value: value
          resources:
            requests:
              cpu: 0.3
              memory: 1024Mi
            limits:
              cpu: 0.5
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - echo 'taotao cloud geteway postStart success' >> /root/postStart
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
        - name: taotao-cloud-uc
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-uc:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: uc-port
              containerPort: 9996
          env:
            - name: LOCAL_KEY
              value: value
          resources:
            requests:
              cpu: 0.3
              memory: 1024Mi
            limits:
              cpu: 0.5
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9996
              scheme: HTTP
            initialDelaySeconds: 360
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9996
            initialDelaySeconds: 360
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - echo 'taotao cloud uc postStart success' >> /root/postStart
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
---

apiVersion: v1
kind: Service
metadata:
  name: taotao-cloud
  namespace: taotao-cloud-dev
  labels:
    app: taotao-cloud
    version: 2021.9.3
spec:
  type: NodePort
  selector:
    app: taotao-cloud
    version: 2021.9.3
  ports:
    - name: gateway-port
      protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 30000
    - name: uc-port
      protocol: TCP
      port: 9996
      targetPort: 9996
      nodePort: 30002
