# Copyright 2002-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: taotao-cloud
  namespace: taotao-cloud-dev
  labels:
    app: taotao-cloud
    version: 2021.9.3
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: taotao-cloud
      version: 2021.9.3
      kubernetes.io/cluster-service: "true"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: taotao-cloud
        version: 2021.9.3
        kubernetes.io/cluster-service: "true"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: taotao-cloud-gateway
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-gateway:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: gateway-port
              containerPort: 33333
          env:
            - name: applicationName
              value: taotao-cloud-gateway
          resources:
            requests:
              cpu: 0.1
              memory: 512Mi
            limits:
              cpu: 0.1
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 33333
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 33333
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - echo 'taotao cloud gateway postStart success' >> /root/postStart
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
        - name: taotao-cloud-admin
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-admin:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: admin-port
              containerPort: 33334
          env:
            - name: applicationName
              value: taotao-cloud-admin
          resources:
            requests:
              cpu: 0.1
              memory: 512Mi
            limits:
              cpu: 0.1
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 33334
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 33334
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - echo 'taotao cloud admin postStart success' >> /root/postStart
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
        - name: taotao-cloud-xxl-job-admin
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-xxl-job-admin:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: admin-port
              containerPort: 33335
          env:
            - name: applicationName
              value: taotao-cloud-xxl-job-admin
          resources:
            requests:
              cpu: 0.1
              memory: 512Mi
            limits:
              cpu: 0.1
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 33335
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 33335
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - echo 'taotao cloud xxl job postStart success' >> /root/postStart
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
        - name: taotao-cloud-oauth2
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-oauth2:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: admin-port
              containerPort: 33336
          env:
            - name: applicationName
              value: taotao-cloud-oauth2
          resources:
            requests:
              cpu: 0.1
              memory: 512Mi
            limits:
              cpu: 0.1
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 33336
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 33336
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - echo 'taotao cloud oauth2 postStart success' >> /root/postStart
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
        - name: taotao-cloud-uc
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-uc:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: uc-port
              containerPort: 33337
          env:
            - name: applicationName
              value: taotao-cloud-uc
          resources:
            requests:
              cpu: 0.1
              memory: 512Mi
            limits:
              cpu: 0.1
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 33337
              scheme: HTTP
            initialDelaySeconds: 360
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 33337
            initialDelaySeconds: 360
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - echo 'taotao cloud uc postStart success' >> /root/postStart
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
        - name: taotao-cloud-order
          image: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-order:2021.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: order-port
              containerPort: 33338
          env:
            - name: applicationName
              value: taotao-cloud-order
          resources:
            requests:
              cpu: 0.1
              memory: 512Mi
            limits:
              cpu: 0.1
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 33338
              scheme: HTTP
            initialDelaySeconds: 360
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 33338
            initialDelaySeconds: 360
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - echo 'taotao cloud order postStart success' >> /root/postStart
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
---

apiVersion: v1
kind: Service
metadata:
  name: taotao-cloud
  namespace: taotao-cloud-dev
  labels:
    app: taotao-cloud
    version: 2021.9.3
spec:
  type: NodePort
  selector:
    app: taotao-cloud
    version: 2021.9.3
  ports:
    - name: gateway-port
      protocol: TCP
      port: 33333
      targetPort: 33333
      nodePort: 33333
    - name: admin-port
      protocol: TCP
      port: 33334
      targetPort: 33334
      nodePort: 33334
    - name: xxl-job-port
      protocol: TCP
      port: 33335
      targetPort: 33335
      nodePort: 33335
    - name: oauth2-port
      protocol: TCP
      port: 33336
      targetPort: 33336
      nodePort: 33336
    - name: uc-port
      protocol: TCP
      port: 33337
      targetPort: 33337
      nodePort: 33337
    - name: order-port
      protocol: TCP
      port: 33338
      targetPort: 33338
      nodePort: 33338
