spring:
  cloud:
    stream:
      ## 消息多个需要在此定义
      function:
        definition: sms,email,order
      bindings:
        sms-out-0:
          destination: sms-topic
          content-type: application/json
        sms-in-0:
          destination: sms-topic
          content-type: text/plain
          group: sms-group
        email-out-0:
          destination: email-topic
          content-type: application/json
        email-in-0:
          destination: email-topic
          content-type: text/plain
          group: email-group
        order-out-0:
          destination: order-topic
          content-type: application/json
        order-in-0:
          destination: order-topic
          content-type: text/plain
          group: order-binder-group

        producer-out-0:
          destination: sql
        consumer-in-0:
          destination: sql
          group: sql-group
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          producer-out-0:
            producer:
              group: output_1
          consumer-in-0:
            consumer:
              #tag: {@code tag1||tag2||tag3 }; sql: {@code 'color'='blue' AND 'price'>100 } .
              subscription: sql:(color in ('red1', 'red2', 'red4') and price>3)


          sms-out-0:
            producer:
              group: sms-binder-group
              sync: true
          sms-in-0:
            consumer:
              orderly: true
          email-out-0:
            producer:
              group: email-binder-group
              sync: true
          email-in-0:
            consumer:
              orderly: true
          order-out-0:
            producer:
              group: order-binder-group
              transactional: true
          order-in-0:
            consumer:
              orderly: true
