spring:
  r2dbc:
    url: r2dbc:mysql://host:3306/taotao-cloud-reactive-order?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    name: r2dbc
    pool.validation-query: SELECT 1
    pool.enabled: true

server:
  port: 8080


knife4j:
  enable: true
