server:
  port: 8888

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: taotao-cloud-admin-server
  sleuth:
    enabled: true
    web:
      client:
        enabled: true
    sampler:
      #采样率，默认为0.1
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://${TAOTAO_CLOUD_ZIPKIN_HOST:127.0.0.1}:${TAOTAO_CLOUD_ZIPKIN_PORT:9411}
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    #发送数据类型 kafaka、rabbitmq、web
    sender:
      type: WEB
  security:
    user:
      name: admin
      password: root123456
  boot:
    admin:
      notify:
        mail:
          enabled: true
          to: 981376577@qq.com
          cc: 981376577@qq.com
          from: Spring Boot Admin <981376577@qq.com>
  mail:
    host: smtp.qq.com
    password: vwdrmsvmevosbeed
    port: 465
    username: 981376577@qq.com

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  health:
    elasticsearch:
      enabled: false
