server:
  port: 10000
  http2:
    enabled: true
  undertow:
    buffer-size: 2048
    direct-buffers: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: taotao-cloud-admin-server
  sleuth:
    enabled: true
    web:
      client:
        enabled: true
    sampler:
      #采样率，默认为0.1
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://${TAOTAO_CLOUD_ZIPKIN_HOST:192.168.1.10}:${TAOTAO_CLOUD_ZIPKIN_PORT:9411}
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    #发送数据类型 kafaka、rabbitmq、web
    sender:
      type: WEB
  boot:
    admin:
      notify:
        mail:
          enabled: true
          to: 981376577@qq.com
          cc: 981376577@qq.com
          from: Spring Boot Admin <981376577@qq.com>
  mail:
    host: smtp.qq.com
    password: ${TAOTAO_CLOUD_MAIL_PASSWORD:taotao-cloud}
    port: 465
    username: 981376577@qq.com
    protocol: smtps
  security:
    user:
      name: admin
      password: root123456
  redis:
    client-name: taotao-cloud-admin-server-redis-client
    host: ${TAOTAO_CLOUD_REDIS_HOST:192.168.1.10}
    port: ${TAOTAO_CLOUD_REDIS_PORT:6379}
    database: 0
    password: ${TAOTAO_CLOUD_REDIS_PASSWORD:taotao-cloud}
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

taotao:
  cloud:
    core:
      enabled: true
      env: dev
      logging:
        file:
          total-size: 10GB
      context:
        restart:
          enabled: false
          text:
          timespan:
      collect:
        hook:
          enabled: true
      db:
        printSql:
          enabled: true
        printSqlError:
          enabled: true
    log:
      request-log:
        enabled: false


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
    env:
      post:
        enabled: true
  metrics:
    enable: true
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  health:
    elasticsearch:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: off
    org.springframework.security: off
    org.springframework.security.oauth2: off
    org.springframework.boot.autoconfigure: off
