spring:
  profiles:
    active: dev

#oauth2:
#  token:
#    issuer: http://127.0.0.1:9000/springauthserver
#
#server:
#  servlet:
#    context-path: /springauthserver
#  port: 9000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    generate-ddl: false
#    show-sql: true
#    properties:
#      hibernate:
#        format-sql: true
#        order_inserts: true
#        order_updates: true
#        jdbc:
#          batch_size: 20
#          fetch_size: 200
#          batch_versioned_data: true
#      jdbc:
#        time_zone: UTC
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:p6spy:mysql://${TAOTAO_CLOUD_MYSQL_HOST:192.168.10.200}:${TAOTAO_CLOUD_MYSQL_PORT:3306}/${spring.application.name}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: ${TAOTAO_CLOUD_MYSQL_USERNAME:root}
#    password: ${TAOTAO_CLOUD_MYSQL_PASSWORD:123456}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      auto-commit: true
#      connection-timeout: 30000
#      idle-timeout: 25000
#      login-timeout: 5
#      validation-timeout: 3000
#      max-lifetime: 50000
#      read-only: false
#      connection-test-query: SELECT 1
#      maximum-pool-size: 15
#      minimum-idle: 10
#      pool-name: DatebookHikariCP
#      register-mbeans: true
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#
#
###########################################################################################################################
##################################################### OAuth2 Token ########################################################
###########################################################################################################################
#
##oauth2:access:token:time : 1
##oauth2:access:token:time:unit : day
##
##oauth2:refresh:token:time : 4
##oauth2:refresh:token:time:unit : day
##
##oauth2:token:issuer : http://127:0:0:1:9000/springauthserver
#
###########################################################################################################################
##################################################### Logging #############################################################
###########################################################################################################################
#
#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    springframework.security.oauth2: INFO
