mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wyu.tt16clickhouse.entity

spring:
  datasource:
    clickhouse:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://106.55.55.249:8123/default
      password: ck的密码
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
    hbase:
      quorum: localhost
      port: 2181
      znode: /hbase
      maxsize: 1572864000
    doris: # doris配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: 数据库地址
      username: 账号
      password: 密码
    presto:
      name: presto
      type: org.apache.tomcat.jdbc.pool.DataSource
      driver-class-name: com.facebook.presto.jdbc.PrestoDriver
      jdbc-url: jdbc:presto://127.0.0.1:8889/hive/test
      username: root
    commonConfig: #连接池统一配置，应用到所有的数据源
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 50
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 10000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      filters: stat

  kafka:
    bootstrap-servers:
      - host:9092
    producer:
      retries: 0
      batch-size: 1073741824
      buffer-memory: 1073741824
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 2
    consumer:
      # 消费组
      group-id: myGroup
      # 消费者是否自动提交偏移量，默认为true
      enable-auto-commit: false
      # 消费者在读取一个没有偏移量或者偏移量无效的情况下，从起始位置读取partition的记录，默认是latest
      auto-offset-reset: earliest
      # 单次调用poll方法能够返回的消息数量
      max-poll-records: 50

logging:
  level:
    root: debug

