server:
  port: 33334
  http2:
    enabled: true
  undertow:
    buffer-size: 2048
    direct-buffers: true
    threads:
      io: 16
      worker: 256
    accesslog:
      dir: ${user.home}/logs/undertow
      enabled: true
  servlet:
    application-display-name: ${spring.application.name}

jasypt:
  encryptor:
    password: ${TAOTAO_CLOUD_ENCRYPTOR_PASSWORD:taotao-cloud}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    property:
      prefix: "ENC@["
      suffix: "]"

redisson:
  password: ${TAOTAO_CLOUD_REDIS_PASSWORD:taotao-cloud}
  single-server-config:
    address: ${TAOTAO_CLOUD_REDIS_HOST:192.168.10.220}:${TAOTAO_CLOUD_REDIS_PORT:6379}

arthas:
  # telnetPort、httpPort为 -1 ，则不listen telnet端口，为 0 ，则随机telnet端口
  # 如果是防止一个机器上启动多个 arthas端口冲突。可以配置为随机端口，或者配置为 -1，并且通过tunnel server来使用arthas。
  # ~/logs/arthas/arthas.log (用户目录下面)里可以找到具体端口日志
  telnetPort: -1
  httpPort: -1
  # 127.0.0.1只能本地访问，0.0.0.0则可网络访问，但是存在安全问题
  ip: 0.0.0.0
  agent-id: ${spring.application.name}
  app-name: ${spring.application.name}
  tunnel-server: ws://192.168.10.220:7777/ws

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  application:
    name: taotao-cloud-open
  sleuth:
    enabled: true
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://${TAOTAO_CLOUD_ZIPKIN_HOST:192.168.10.200}:${TAOTAO_CLOUD_ZIPKIN_PORT:9411}
    discoveryClientEnabled: false
    sender:
      type: WEB
  redis:
    #host: ${TAOTAO_CLOUD_REDIS_HOST:192.168.10.200}
    #port: ${TAOTAO_CLOUD_REDIS_PORT:6379}
    #database: 1
    #password: ${TAOTAO_CLOUD_REDIS_PASSWORD:taotao-cloud}
    connect-timeout: 60000
    cluster:
      nodes: 192.168.10.200:7100,192.168.10.200:7101,192.168.10.200:7102,192.168.10.200:7103,192.168.10.200:7104,192.168.10.200:7105
      max-redirects: 3
    #sentinel:
    #  master:
    #  nodes:
    client-type: lettuce
    lettuce:
      pool:
        max-active: 1500
        max-wait: 5000
        max-idle: 500
        min-idle: 100
    redisson:
      config: |
        clusterServersConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          failedSlaveReconnectionInterval: 3000
          failedSlaveCheckInterval: 60000
          password: null
          subscriptionsPerConnection: 5
          clientName: null
          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          slaveConnectionMinimumIdleSize: 24
          slaveConnectionPoolSize: 64
          masterConnectionMinimumIdleSize: 24
          masterConnectionPoolSize: 64
          readMode: "SLAVE"
          subscriptionMode: "SLAVE"
          nodeAddresses:
          - "redis://192.168.10.200:7100"
          - "redis://192.168.10.200:7101"
          - "redis://192.168.10.200:7102"
          - "redis://192.168.10.200:7103"
          - "redis://192.168.10.200:7104"
          - "redis://192.168.10.200:7105"
          scanInterval: 1000
          pingConnectionInterval: 0
          keepAlive: false
          tcpNoDelay: false
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.MarshallingCodec> {}
        transportMode: "NIO"
  kafka:
    bootstrap-servers: ${TAOTAO_CLOUD_KAFKA_HOST:192.168.10.200}:${TAOTAO_CLOUD_KAFKA_PORT:9092}
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 0
      properties:
        linger.ms: 100
    consumer:
      auto-commit-interval: 1S
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 5
      ack-mode: manual_immediate
      missing-topics-fatal: false

taotao:
  cloud:
    prometheus:
      enabled: true
    dinger:
      enabled: true
      httpclient:
        enabled: true
      threadpool:
        enabled: true
      project-id: ${spring.application.name}
      dingers:
        dingtalk:
          tokenId: ${DINGDING_TOKEN_ID:2f81a18fd235ffbecc00519d53bb8054a7ff3e50f3287e3e4c5fef6e5c8e1016}
          secret: ${DINGDING_SECRET:SEC2ec149b6eaab26a16b3d6c78845848251d0667fb8aa288b0e79d8675e4608d80}
    core:
      enabled: true
      env: dev
    openapi:
      enabled: true
      server: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
    env:
      post:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  health:
    elasticsearch:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: off
    org.springframework.security: off
    org.springframework.security.oauth2: off
    org.springframework.boot.autoconfigure: off

#对非对称加密密钥对
keys:
  local:
    rsa:
      privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALIDA5vuI23/6mPaSy71zwmWWH/ZvarIxI2TQnlV6ZDFZkMRM0SuI5CamnTeiFkzFOApa/jw5nzkl8tXTllTJ4sFu7IdInPJHP/rkora3PncFE/ypsaZfifDyocvrP/sePnftvn2lbHBlKgnRoLLhRRXQFjol7C3gadK8gZMAe2hAgMBAAECgYAoJRFejEM9tqnpuGxdrA4zq44MUTLardnT0sq6OeOJZFcmV13wRnRbU15zbk8iDKjPz8+bjdpw/o10DF2tO9lN+cHBHpUj4uKIiUj1DJZTiHIuwS0uXb5F+UEHga30grunHdPP2XMcbcvCKBDq8d7WwUzXnWLUkSVl9CWT97zHtQJBAPjrMNIr+bhHEZHkVzdUdELGa9FEIpUzx2dYcpnX91dfsjXIE7QGzUWFilKZtDae9Fa6az1yMDS0K3Z750zxyPUCQQC3E21G40ta3NfvjgocZr+IaZ0/JfJ6VKlMosYc+/aoAHUMqx+oQTf2+oSy6SlqpwW+zjyCf9hEp9FGDDFKXtZ9AkEAj8s1ycPTn2uWr8PLyk/EVarQL/R/Ude2knHayhqjbNsAVOc+0pm3TTkGng7it0b9+Xf5aWakiF2oWerbxGxMXQJAGUiij+a2Mn9LhzcLqG58Rz+myuDXwxNMKlxUlg4qO3uMrso3Xgpby00/5GGVKbiVb4uWCcPUP28Z1N28NPQyFQJBAJC9Pts+nCAo/jGtmIB0W9riAmDSpYbosxYhDfbDrazoa5Q12zNNUdmivag6hZ3kY+Ne2v3+jH6iwdSZE7aLT8I=
      publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyAwOb7iNt/+pj2ksu9c8Jllh/2b2qyMSNk0J5VemQxWZDETNEriOQmpp03ohZMxTgKWv48OZ85JfLV05ZUyeLBbuyHSJzyRz/65KK2tz53BRP8qbGmX4nw8qHL6z/7Hj537b59pWxwZSoJ0aCy4UUV0BY6Jewt4GnSvIGTAHtoQIDAQAB
    sm2:
      privateKey: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgXhrlBH9kaWuNj3nkNWl7qB2wUbqd29E1LwlWYBOjJCygCgYIKoEcz1UBgi2hRANCAAQBVac94mZDZGFqnvcEkIH6WWybWG+Pz2HRq4AfF6WW4wntviwU+mw6ZxcKCsLS4pljRxF3bPoR+18VnVXkEpWz
      publicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEAVWnPeJmQ2Rhap73BJCB+llsm1hvj89h0auAHxelluMJ7b4sFPpsOmcXCgrC0uKZY0cRd2z6EftfFZ1V5BKVsw==
  remote:
    rsa:
      publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDSYZnCTa66CGJwCb3FP5nbFIOkrY+xJdu3siGFzpr/GAe/COkRUrmzP+vo0om6GxPkEVAfxZaLw8tH8FCkJ1+BQI2cztUQhDsHyXP4xAsq7RPtoYEjXB0+mLByorWDFkR/K3KfZU/iBkyry/jG2GKMJ/73HPXLv4hvwW96p4lb8QIDAQAB
    sm2:
      publicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEZ0YWLsv6Kco6nwg9hKO83wAzOk3Eg+IXH91tgK4j+sOmBmjo2GLwQHrbiC1471ThqVWK63f3/B9cRTXqwuckEA==

