server:
  http:
    port: 9900
  port: 9443
  shutdown: graceful
  http2:
    enabled: true
  ssl:
    enabled: false
    key-store: classpath:cert/SHA256withRSA_taotaocloud.top.jks
    key-store-type: JKS
    key-store-password: 1234

spring:
  cache:
    type: none
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  application:
    name: taotao-cloud-gateway-service
  redis:
    client-name: taotao-cloud-gateway-redis-client
    host: ${TAOTAO-CLOUD-REDIS-HOST:192.168.1.10}
    port: ${TAOTAO-CLOUD-REDIS-PORT:6379}
    database: 0
    password: ${TAOTAO-CLOUD-REDIS-PASSWORD:taotao-cloud}
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  kafka:
    bootstrap-servers: ${TAOTAO-CLOUD-KAFKA-HOST:192.168.1.10}:${TAOTAO-CLOUD-KAFKA-PORT:9092}
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
      properties:
        linger.ms: 500
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      discovery:
        server-addr: ${TAOTAO_CLOUD_NACOS_DISCOVERY_HOST:192.168.1.10}:${TAOTAO_CLOUD_NACOS_DISCOVERY_PORT:8848}
        metadata:
          version: 4
      config:
        enabled: false
        server-addr: ${TAOTAO_CLOUD_NACOS_CONFIG_HOST:192.168.1.10}:${TAOTAO_CLOUD_NACOS_CONFIG_PORT:8848}
        namespace: f402a0ea-5ce7-43cc-b19b-3fb7ded6e46e
        file-extension: yml
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: ${TAOTAO-CLOUD-SENTINEL-DASHBOARD-HOST:192.168.1.10}:${TAOTAO-CLOUD-SENTINEL-DASHBOARD-PORT:8858}
        port: ${TAOTAO-CLOUD-SENTINEL-PORT:8718}
      scg:
        fallback:
          mode: response
          response-status: 200
          response-body: "{'data': null, 'code': 500,'message': '访问频繁,进入系统熔断'}"
    gateway:
      loadbalancer:
        use404: false
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: taotao-cloud-uc-service
          uri: lb://taotao-cloud-uc-service
          predicates:
            - Path=/taotao-cloud-uc-service/**
          filters:
            - RewritePath=/taotao-cloud-uc-service/(?<remaining>.*), /${remaining}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

      default-filters:
        - AddRequestHeader=X-Request-taotao-cloud, 1.0
#  sleuth:
#    web:
#      client:
#        enabled: false
#    sampler:
#      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
#  zipkin:
#    enabled: false
#    sender:
#      type: kafka

taotao:
  cloud:
    gateway:
      prefix: /api
      version: /v1.0
      dynamic:
        route:
          enabled: false
          type: nacos
      log:
        trace:
          enabled: true
      security:
        ignore:
          http-urls: >
            /*/api-docs,
            /code,
            /uc/repeat/check,
            /uc/user,
            /auth/client,
            /manager/graphql,
            /manager/graphiql,
            /auth/oauth/**,
            /auth/mobile/login,
            /auth/sms/code,
            /auth/social/**,
            /auth/css/**,
            /auth/images/**,
            /auth/js/**,
            /favicon.ico,
            /manifest.json,
            /robots.txt
        auth:
          renew:
            enabled: true
    log:
      enabled: true
      types:
        - kafka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
knife4j:
  enable: false
