server:
  http:
    port: 9900
  port: 9443
  shutdown: graceful
  http2:
    enabled: true
#  ssl:
#    enabled: true
#    key-store: classpath:cert/SHA256withRSA_taotaocloud.top.jks
#    key-store-type: JKS
#    key-store-password: 1234


spring:
  cache:
    type: none
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: taotao-cloud-gateway-service
  redis:
    client-name: taotao-cloud-gateway-redis-client
    host: ${TAOTAO-CLOUD-REDIS-HOST:host}
    port: ${TAOTAO-CLOUD-REDIS-PORT:6379}
    database: 0
    password: ${TAOTAO-CLOUD-REDIS-PASSWORD:taotao-cloud}
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  kafka:
    bootstrap-servers: ${TAOTAO-CLOUD-KAFKA-HOST}:${TAOTAO-CLOUD-KAFKA-PORT}
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
      properties:
        linger.ms: 500
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
#    nacos:
#      discovery:
#        server-addr: 103.218.242.48:${TAOTAO_CLOUD_NACOS_DISCOVERY_PORT}
#        metadata:
#          version: 4
#      config:
#        enabled: false
#        server-addr: ${TAOTAO_CLOUD_NACOS_CONFIG_HOST:host}:${TAOTAO_CLOUD_NACOS_CONFIG_PORT:8848}
#        namespace: f402a0ea-5ce7-43cc-b19b-3fb7ded6e46e
#        file-extension: yml
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: ${TAOTAO-CLOUD-SENTINEL-DASHBOARD-HOST:host}:${TAOTAO-CLOUD-SENTINEL-DASHBOARD-PORT:8858}
        port: ${TAOTAO-CLOUD-SENTINEL-PORT:8718}
      scg:
        fallback:
          mode: response
          response-status: 200
          response-body: "{'data': null, 'code': 500,'message': '访问频繁,进入系统熔断'}"
    gateway:
      loadbalancer:
        use404: false
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: auth-user-password-token
          uri: lb://taotao-cloud-auth-service
          predicates:
            - Path=/auth/oauth/token/user
          filters:
            - StripPrefix=3
            
            - PreserveHostHeader
        - id: auth-login-third-token
          uri: lb://taotao-cloud-auth-service
          predicates:
            - Path=http:///auth/oauth/token/third
          filters:
            - StripPrefix=3
            
            - PreserveHostHeader
        # 发送短信接口要做接口限制
        - id: auth-sms-code
          uri: lb://taotao-cloud-auth-service
          predicates:
            - Path=http:///auth/sms/code
          filters:
            - StripPrefix=3
            
            - PreserveHostHeader
        # 数据重复校验要做接口限制
        - id: uc-repeact-check
          uri: lb://taotao-cloud-uc-service
          predicates:
            - Path=http:///uc/repeat/check
          filters:
            - StripPrefix=3
            
            - PreserveHostHeader
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: taotao-cloud-uc-service
          uri: lb://taotao-cloud-uc-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
            - StripPrefix=3
            - PreserveHostHeader
        - id: taotao-cloud-auth-service
          uri: lb://taotao-cloud-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=3
            - PreserveHostHeader
        - id: taotao-cloud-order-service
          uri: lb://taotao-cloud-order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-aftersale-service
          uri: lb://taotao-cloud-aftersale-service
          predicates:
            - Path=/aftersale/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-customer-service
          uri: lb://taotao-cloud-customer-service
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-dfs-service
          uri: lb://taotao-cloud-dfs-service
          predicates:
            - Path=/dfs/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-pay-service
          uri: lb://taotao-cloud-pay-service
          predicates:
            - Path=/pay/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-log-service
          uri: lb://taotao-cloud-log-service
          predicates:
            - Path=/log/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-member-service
          uri: lb://taotao-cloud-member-service
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-mail-service
          uri: lb://taotao-cloud-mail-service
          predicates:
            - Path=/mail/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-logistics-service
          uri: lb://taotao-cloud-logistics-service
          predicates:
            - Path=/logistics/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-manager-service
          uri: lb://taotao-cloud-manager-service
          predicates:
            - Path=/manager/**
          filters:
            - StripPrefix=3
        - id: taotao-cloud-product-service
          uri: lb://taotao-cloud-product-service
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=3
      default-filters:
        - AddRequestHeader=X-Request-taotao-cloud, 1.0
#  sleuth:
#    web:
#      client:
#        enabled: false
#    sampler:
#      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
#  zipkin:
#    enabled: false
#    sender:
#      type: kafka

taotao:
  cloud:
    gateway:
      prefix: /api
      version: /v1.0
      dynamic:
        route:
          enabled: false
          type: nacos
      log:
        trace:
          enabled: true
      swagger-agg:
        enabled: true
        api-docs-path: /api-docs
        swagger-version: 2.0
        generate-routes:
          - taotao-cloud-uc-service
          - taotao-cloud-auth-service
          - taotao-cloud-order-service
          - taotao-cloud-product-service
          - taotao-cloud-aftersale-service
          - taotao-cloud-customer-service
          - taotao-cloud-dfs-service
          - taotao-cloud-log-service
          - taotao-cloud-logistics-service
          - taotao-cloud-mail-service
          - taotao-cloud-member-service
          - taotao-cloud-pay-service
    oauth2:
      token:
        store:
          type: redis
      security:
        ignore:
          http-urls: >
            /*/api-docs,
            /code,
            /uc/repeat/check,
            /uc/user,
            /auth/client,
            /manager/graphql,
            /manager/graphiql,
            /auth/oauth/**,
            /auth/mobile/login,
            /auth/sms/code,
            /auth/social/**,
            /auth/css/**,
            /auth/images/**,
            /auth/js/**,
            /favicon.ico,
            /manifest.json,
            /robots.txt
        auth:
          renew:
            enabled: true
    log:
      types:
        - kafka
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
knife4j:
  enable: false
