server:
  port: 9100

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
  security:
    oauth2:
      client:
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
          qq:
            authorizationUri: https://graph.qq.com/oauth2.0/authorize
            tokenUri: https://graph.qq.com/oauth2.0/token
            userInfoUri: https://graph.qq.com/user/get_user_info
            userNameAttribute: nickname
        registration:
          gitee:
            client-id: 81bc2a5852cbcd35f94fa77512e1efb776b57102e1fb9b82105acf7b412f072b
            client-secret: 6cf101f97728215e3455d19bf84e4b277be505a9690cf0e9558bc24904dd6ad6
            authorization-grant-type: authorization_code
            redirect-uri: http://9da31b1edd0e.ngrok.io/api/login/oauth2/code/gitee
          github:
            clientId: Iv1.f4c52616ef60f7be
            clientSecret: e2c1524fefec9a18a459fb863ceaa8655f7899f1
            redirectUri: http://0b817f4ac311.ngrok.io/api/login/oauth2/code/github
          qq:
            clientId: clientId
            clientSecret: clientSecret
            # 在本地测试时需要配置代理将自己在qq注册的redirectUri重定向为http://localhost/api/login/oauth2/code/qq
            redirectUri: https://www.zyc.red/api/login/oauth2/code/qq
            authorizationGrantType: authorization_code
            # 授权码模式需要传递code、state、client_id、client_secret等参数，OAuth2AuthorizationCodeGrantRequestEntityConverter
            # 会根据当前的认证方式传递不同的参数
            clientAuthenticationMethod: post
      resourceserver:
#        jwt:
#          public-key-location: classpath:key.public
#          jws-algorithm: RS512
#        opaquetoken:
#          introspection-uri: http://localhost:9000/oauth/check_token
#          client-id: abc
#          client-secret: abc
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks

logging:
  level:
    org.springframework.security: debug

