spring:
  cloud:
    compatibility-verifier:
      enabled: false
    loadbalancer:
      enabled: true
    function:
      # functionName对应服务中的Bean
      definition: inputKafka1;inputKafka2;inputRabbit1;inputRabbit2
    stream:
      bindings:
        sms-output:
          destination: sms-topic
          binder: rabbit
        sms-input:
          destination: sms-topic
          group: sms-group
          binder: rabbit
        email-output:
          destination: email-topic
          #content-type: application/json
          binder: rocketmq
        email-input:
          destination: email-topic
          group: email-group
          binder: rocketmq
          consumer:
            #并发消费线程数
            concurrency: 20
        order-output:
          destination: order-topic
          #content-type: application/json
          binder: kafka
        order-input:
          destination: order-topic
          group: order-group
          binder: kafka
        # function kafka binding
        outputKafka-out-0:
          binder: kafka
          destination: destination-test-kafka-topic
        inputKafka1-in-0:
          binder: kafka
          destination: destination-test-kafka-topic
          group: group1
        inputKafka2-in-0:
          binder: kafka
          destination: destination-test-kafka-topic
          group: group2
        # function rabbit binding
        outputRabbit-out-0:
          binder: rabbit
          destination: destination-test-rabbit
          producer:
            partitioned: true
            partition-key-expression: headers['partitionKey']
            partition-count: 2
            required-groups:
              - myGroup
        inputRabbit1-in-0:
          binder: rabbit
          destination: destination-test-rabbit
          group: group1
        inputRabbit2-in-0:
          binder: rabbit
          destination: destination-test-rabbit
          group: group2
      rocketmq:
        binder:
          name-server: 192.168.244.128:9876;192.168.244.129:9876;
      rabbit:
        binder:
          admin-addresses: 172.16.6.151:5672,172.16.6.151:5672,
        bindings:
          sms-output:
            producer:
              #routing-key-expression: headers.routingKey   # 发送端路由key
              delayed-exchange: false    # 开启延时队列
          sms-input:
            consumer:
              #binding-routing-key: login.user.succeed   # 生产监听路由表达式
              delayed-exchange: false    # 开启延时队列
              #auto-bind-dlq: true   # 绑定死信队列
              #republish-to-dlq: true  # 重投到死信队列并带有报错信息
      kafka:
        binder:
          brokers: 172.16.6.151:9092
          auto-create-topics: true
          autoAddPartitions: true
        bindings:
          order-output:
            producer:
              sync: true
              bufferSize: 16384
          order-input:
            consumer:
              txCommitRecovered: true
