name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ v1 ]

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Gradle And Build the Docker image
      working-directory: .
      run: |
        ls -la $PWD,
        ls -la $GITHUB_WORKSPACE,
        cd ../../taotao-cloud-microservice/taotao-cloud-admin,
        gradle clean bootJar,
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} registry.cn-hangzhou.aliyuncs.com,
        docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-admin:2021.10.1,
        docker push registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-admin:2021.10.1

