name: assemble open

on:
  push:
    paths:
      - 'taotao-cloud-web/taotao-cloud-open/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

defaults:
  run:
    working-directory: ./taotao-cloud-web/taotao-cloud-open

env:
  TAOTAO_CLOUD_VERSION: 2022.01

jobs:
  assemble:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'taotao-cloud-open') }}
    steps:
      - name: checkout project
        uses: actions/checkout@master

      - name: use node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: cache node_modules folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules

      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache yarn
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install and build
        run: |
          yarn
          yarn build

      - name: deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "taotao-cloud-web/taotao-cloud-open/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_OPEN_TARGET }}

      - name: build docker image taotao-cloud-open
        run: |
          docker login -u ${{ secrets.TAOTAO_CLOUD_REGISTRY_USERNAME }} -p ${{ secrets.TAOTAO_CLOUD_REGISTRY_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          ls -l
          docker build --tag registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-open:${{env.TAOTAO_CLOUD_VERSION}} .
          docker push registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-open:${{env.TAOTAO_CLOUD_VERSION}}
